name : artifact-test
on:
 push:
   branches:
      main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        uses: actions/checkout@v3

      - name: job2
        run: |
             echo "'new items are pushed to the main branch test 1 ',${{github.ref}}"  
             echo "'github user :' ,{{github.actor}}"
             echo "'github repository',{{github.repository}}"
    
