name : artifact-test
on:
 push:
   branches:
      main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        uses: actions/checkout@v3

      - name: job2
        run: |
          echo "'new items are pushed to the main branch test 1', ${{github.ref}}" >> output.txt  
          echo "'github user:', ${{github.actor}}" >> output.txt
          echo "'github repository:', ${{github.repository}}" >> output.txt

      - name: job3
        uses: actions/upload-artifact@v3
        with:
          name: job2-logs
          path: output.txt 

  job12:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: job2-logs
          path: ./downloads

      - name: Display All Contents
        run: cat ./downloads/output.txt
           
        
        
    
