name : artifact-test
on:
 push:
   branches:
      main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        uses: action/checkout@v3

      - name: job2
        run: echo"'new items are pushed to the main branch'"  
  
    
